In [1]:
import pandas as pd
import os

try:
    import urllib2 as urllib
except ImportError:
    import urllib as urllib

%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [14]:
url = "http://web.mta.info/developers/data/nyct/turnstile/turnstile_180929.txt"
urllib.request.urlretrieve(url, "turnstile.csv")
!mv turnstile.csv $HOME/USAProject2

In [15]:
turnstile = pd.read_csv(os.getenv('HOME') + '/USAProject2/turnstile.csv')

In [4]:
turnstile.head()

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,09/22/2018,00:00:00,REGULAR,6767488,2294227
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,09/22/2018,04:00:00,REGULAR,6767499,2294230
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,09/22/2018,08:00:00,REGULAR,6767517,2294258
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,09/22/2018,12:00:00,REGULAR,6767607,2294323
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,09/22/2018,16:00:00,REGULAR,6767790,2294368

In [40]:
unique(turnstile['STATION'])

array(['1 AV', '103 ST', '103 ST-CORONA', '104 ST', '110 ST', '111 ST',
       '116 ST', '116 ST-COLUMBIA', '121 ST', '125 ST', '135 ST',
       '137 ST CITY COL', '138/GRAND CONC', '14 ST', '14 ST-UNION SQ',
       '145 ST', '149/GRAND CONC', '14TH STREET', '15 ST-PROSPECT',
       '155 ST', '157 ST', '161/YANKEE STAD', '163 ST-AMSTERDM', '167 ST',
       '168 ST', '169 ST', '170 ST', '174 ST', '175 ST', '176 ST', '18 AV',
       '18 ST', '181 ST', '182-183 STS', '183 ST', '190 ST', '191 ST',
       '2 AV', '20 AV', '207 ST', '21 ST', '21 ST-QNSBRIDGE', '215 ST',
       '219 ST', '225 ST', '23 ST', '231 ST', '233 ST', '238 ST', '25 AV',
       '25 ST', '28 ST', '3 AV', '3 AV 138 ST', '3 AV-149 ST', '30 AV',
       '33 ST', '33 ST-RAWSON ST', '34 ST-HERALD SQ', '34 ST-HUDSON YD',
       '34 ST-PENN STA', '36 AV', '36 ST', '4 AV-9 ST', '40 ST LOWERY ST',
       '42 ST-BRYANT PK', '42 ST-PORT AUTH', '45 ST', '46 ST',
       '46 ST BLISS ST', '47-50 STS ROCK', '49 ST', '4AV-9 ST',
       '5 AV/53 ST', '5 AV/59 ST', '5 AVE', '50 ST', '51 ST', '52 ST',
       '53 ST', '55 ST', '57 ST-7 AV', '59 ST', '59 ST COLUMBUS', '6 AV',
       '61 ST WOODSIDE', '63 DR-REGO PARK', '65 ST', '66 ST-LINCOLN',
       '67 AV', '68ST-HUNTER CO', '69 ST', '7 AV', '71 ST', '72 ST',
       '72 ST-2 AVE', '74 ST-BROADWAY', '75 AV', '75 ST-ELDERTS', '77 ST',
       '79 ST', '8 AV', '8 ST-NYU', '80 ST', '81 ST-MUSEUM',
       '82 ST-JACKSON H', '85 ST-FOREST PK', '86 ST', '86 ST-2 AVE',
       '88 ST', '9 AV', '90 ST-ELMHURST', '96 ST', '96 ST-2 AVE',
       '9TH STREET', 'ALABAMA AV', 'ALLERTON AV', 'AQUEDUCT N.COND',
       'AQUEDUCT RACETR', 'ASTOR PL', 'ASTORIA BLVD', 'ASTORIA DITMARS',
       'ATL AV-BARCLAY', 'ATLANTIC AV', 'AVENUE H', 'AVENUE I', 'AVENUE J',
       'AVENUE M', 'AVENUE N', 'AVENUE P', 'AVENUE U', 'AVENUE X',
       "B'WAY-LAFAYETTE", 'BAY 50 ST', 'BAY PKWY', 'BAY RIDGE AV',
       'BAY RIDGE-95 ST', 'BAYCHESTER AV', 'BEACH 105 ST', 'BEACH 25 ST',
       'BEACH 36 ST', 'BEACH 44 ST', 'BEACH 60 ST', 'BEACH 67 ST',
       'BEACH 90 ST', 'BEACH 98 ST', 'BEDFORD AV', 'BEDFORD PK BLVD',
       'BEDFORD-NOSTRAN', 'BERGEN ST', 'BEVERLEY ROAD', 'BEVERLY RD',
       'BLEECKER ST', 'BOROUGH HALL', 'BOTANIC GARDEN', 'BOWERY',
       'BOWLING GREEN', 'BRIARWOOD', 'BRIGHTON BEACH', 'BROAD CHANNEL',
       'BROAD ST', 'BROADWAY', 'BROADWAY JCT', 'BRONX PARK EAST',
       'BROOK AV', 'BROOKLYN BRIDGE', 'BUHRE AV', 'BURKE AV',
       'BURNSIDE AV', 'BUSHWICK AV', 'CANAL ST', 'CANARSIE-ROCKAW',
       'CARROLL ST', 'CASTLE HILL AV', 'CATHEDRAL PKWY', 'CENTRAL AV',
       'CENTRAL PK N110', 'CHAMBERS ST', 'CHAUNCEY ST', 'CHRISTOPHER ST',
       'CHURCH AV', 'CITY / BUS', 'CITY HALL', 'CLARK ST', 'CLASSON AV',
       'CLEVELAND ST', 'CLINTON-WASH AV', 'CONEY IS-STILLW',
       'CORTELYOU RD', 'CORTLANDT ST', 'COURT SQ', 'COURT SQ-23 ST',
       'CRESCENT ST', 'CROWN HTS-UTICA', 'CYPRESS AV', 'CYPRESS HILLS',
       'DEKALB AV', 'DELANCEY/ESSEX', 'DITMAS AV', 'DYCKMAN ST',
       "E 143/ST MARY'S", 'E 149 ST', 'E 180 ST', 'EAST 105 ST',
       'EAST BROADWAY', 'EASTCHSTER/DYRE', 'EASTN PKWY-MUSM', 'ELDER AV',
       'ELMHURST AV', 'EUCLID AV', 'EXCHANGE PLACE', 'FAR ROCKAWAY',
       'FLATBUSH AV-B.C', 'FLUSHING AV', 'FLUSHING-MAIN', 'FORDHAM RD',
       'FOREST AVE', 'FOREST HILLS 71', 'FRANKLIN AV', 'FRANKLIN ST',
       'FREEMAN ST', 'FRESH POND RD', 'FT HAMILTON PKY', 'FULTON ST',
       'GATES AV', 'GRAHAM AV', 'GRAND ARMY PLAZ', 'GRAND ST',
       'GRAND-NEWTOWN', 'GRANT AV', 'GRD CNTRL-42 ST', 'GREENPOINT AV',
       'GROVE STREET', 'GUN HILL RD', 'HALSEY ST', 'HARLEM 148 ST',
       'HARRISON', 'HEWES ST', 'HIGH ST', 'HOUSTON ST', 'HOWARD BCH JFK',
       'HOYT ST', 'HOYT-SCHER', 'HUNTERS PT AV', 'HUNTS POINT AV',
       'INTERVALE AV', 'INWOOD-207 ST', 'JACKSON AV', 'JAMAICA 179 ST',
       'JAMAICA CENTER', 'JAMAICA VAN WK', 'JAY ST-METROTEC',
       'JEFFERSON ST', 'JFK JAMAICA CT1', 'JKSN HT-ROOSVLT',
       'JOURNAL SQUARE', 'JUNCTION BLVD', 'JUNIUS ST', 'KEW GARDENS',
       'KINGS HWY', 'KINGSBRIDGE RD', 'KINGSTON AV', 'KINGSTON-THROOP',
       'KNICKERBOCKER', 'KOSCIUSZKO ST', 'LACKAWANNA', 'LAFAYETTE AV',
       'LEXINGTON AV/53', 'LEXINGTON AV/63', 'LIBERTY AV', 'LIVONIA AV',
       'LONGWOOD AV', 'LORIMER ST', 'MARBLE HILL-225', 'MARCY AV',
       'METROPOLITAN AV', 'METS-WILLETS PT', 'MIDDLETOWN RD',
       'MONTROSE AV', 'MORGAN AV', 'MORISN AV/SNDVW', 'MORRIS PARK',
       'MOSHOLU PKWY', 'MT EDEN AV', 'MYRTLE AV', 'MYRTLE-WILLOUGH',
       'MYRTLE-WYCKOFF', 'NASSAU AV', 'NECK RD', 'NEPTUNE AV', 'NEREID AV',
       'NEVINS ST', 'NEW LOTS', 'NEW LOTS AV', 'NEW UTRECHT AV',
       'NEWARK BM BW', 'NEWARK C', 'NEWARK HM HE', 'NEWARK HW BMEBE',
       'NEWKIRK AV', 'NEWKIRK PLAZA', 'NORTHERN BLVD', 'NORWOOD 205 ST',
       'NORWOOD AV', 'NOSTRAND AV', 'OCEAN PKWY', 'OZONE PK LEFFRT',
       'PARK PLACE', 'PARKCHESTER', 'PARKSIDE AV', 'PARSONS BLVD',
       'PATH NEW WTC', 'PATH WTC 2', 'PAVONIA/NEWPORT', 'PELHAM BAY PARK',
       'PELHAM PKWY', 'PENNSYLVANIA AV', 'PRESIDENT ST', 'PRINCE ST',
       'PROSPECT AV', 'PROSPECT PARK', 'QUEENS PLAZA', 'QUEENSBORO PLZ',
       'RALPH AV', 'RECTOR ST', 'RIT-MANHATTAN', 'RIT-ROOSEVELT',
       'ROCKAWAY AV', 'ROCKAWAY BLVD', 'ROCKAWAY PARK B',
       'ROOSEVELT ISLND', 'SARATOGA AV', 'SENECA AVE', 'SHEEPSHEAD BAY',
       'SHEPHERD AV', 'SIMPSON ST', 'SMITH-9 ST', 'SOUTH FERRY',
       'SPRING ST', 'ST LAWRENCE AV', 'ST. GEORGE', 'STEINWAY ST',
       'STERLING ST', 'SUTPHIN BLVD', 'SUTPHIN-ARCHER', 'SUTTER AV',
       'SUTTER AV-RUTLD', 'THIRTY ST', 'THIRTY THIRD ST', 'TIMES SQ-42 ST',
       'TOMPKINSVILLE', 'TREMONT AV', 'TWENTY THIRD ST', 'UNION ST',
       'UTICA AV', 'V.CORTLANDT PK', 'VAN SICLEN AV', 'VAN SICLEN AVE',
       'VERNON-JACKSON', 'W 4 ST-WASH SQ', 'W 8 ST-AQUARIUM',
       'WAKEFIELD/241', 'WALL ST', 'WEST FARMS SQ', 'WESTCHESTER SQ',
       'WHITEHALL S-FRY', 'WHITLOCK AV', 'WILSON AV', 'WINTHROP ST',
       'WOODHAVEN BLVD', 'WOODLAWN', 'WORLD TRADE CTR', 'YORK ST',
       'ZEREGA AV'], dtype=object)

In [39]:
# want exits that occur after 8.00pm and before midnight

turnstile8pm = turnstile[turnstile['TIME'] ==  '00:00:00']
turnstile8pm0922 = turnstile8pm[turnstile8pm['DATE'] == '09/22/2018']
turnstile8pm0922.sort_values(by='UNIT')

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
38735,J025,R003,00-00-00,CYPRESS HILLS,J,BMT,09/22/2018,00:00:00,REGULAR,423545,497553
38777,J025,R003,00-00-01,CYPRESS HILLS,J,BMT,09/22/2018,00:00:00,REGULAR,1828295,768083
38819,J025,R003,00-00-02,CYPRESS HILLS,J,BMT,09/22/2018,00:00:00,REGULAR,4580624,2789763
38990,J028,R004,00-00-03,75 ST-ELDERTS,JZ,BMT,09/22/2018,00:00:00,REGULAR,973728,1947509
38861,J028,R004,00-00-00,75 ST-ELDERTS,JZ,BMT,09/22/2018,00:00:00,REGULAR,365,457
38904,J028,R004,00-00-01,75 ST-ELDERTS,JZ,BMT,09/22/2018,00:00:00,REGULAR,4102052,3418561
38947,J028,R004,00-00-02,75 ST-ELDERTS,JZ,BMT,09/22/2018,00:00:00,REGULAR,699611,572145
39033,J028,R004,00-00-04,75 ST-ELDERTS,JZ,BMT,09/22/2018,00:00:00,REGULAR,5763528,4251794
39162,J030,R005,00-00-02,85 ST-FOREST PK,J,BMT,09/22/2018,00:00:00,REGULAR,251460,154797
39205,J030,R005,00-00-03,85 ST-FOREST PK,J,BMT,09/22/2018,00:00:00,REGULAR,7266406,6326022
39076,J030,R005,00-00-00,85 ST-FOREST PK,J,BMT,09/22/2018,00:00:00,REGULAR,7626778,7161674
39119,J030,R005,00-00-01,85 ST-FOREST PK,J,BMT,09/22/2018,00:00:00,REGULAR,4915177,2950414
39374,J031,R006,00-00-03,WOODHAVEN BLVD,JZ,BMT,09/22/2018,00:00:00,REGULAR,7724537,5209389
39290,J031,R006,00-00-01,WOODHAVEN BLVD,JZ,BMT,09/22/2018,00:00:00,REGULAR,2254246,1525034
39248,J031,R006,00-00-00,WOODHAVEN BLVD,JZ,BMT,09/22/2018,00:00:00,REGULAR,4632426,6091322
39458,J032,R006,01-05-01,WOODHAVEN BLVD,JZ,BMT,09/22/2018,00:00:00,REGULAR,458752,39
39416,J032,R006,01-05-00,WOODHAVEN BLVD,JZ,BMT,09/22/2018,00:00:00,REGULAR,33554675,0
39332,J031,R006,00-00-02,WOODHAVEN BLVD,JZ,BMT,09/22/2018,00:00:00,REGULAR,4118805,2091602
39542,J032,R006,01-06-01,WOODHAVEN BLVD,JZ,BMT,09/22/2018,00:00:00,REGULAR,1195275,202649
39500,J032,R006,01-06-00,WOODHAVEN BLVD,JZ,BMT,09/22/2018,00:00:00,REGULAR,1575884,695093
39625,J034,R007,00-00-01,104 ST,JZ,BMT,09/22/2018,00:00:00,REGULAR,1121224034,1907534708
39709,J034,R007,00-00-03,104 ST,JZ,BMT,09/22/2018,00:00:00,REGULAR,4442983,4693947
39583,J034,R007,00-00-00,104 ST,JZ,BMT,09/22/2018,00:00:00,REGULAR,5975120,4843329
39667,J034,R007,00-00-02,104 ST,JZ,BMT,09/22/2018,00:00:00,REGULAR,2025953304,622100512
39751,J035,R008,00-00-00,111 ST,J,BMT,09/22/2018,00:00:00,REGULAR,3681801,5189539
39835,J035,R008,00-00-02,111 ST,J,BMT,09/22/2018,00:00:00,REGULAR,3748466,2161834
39877,J035,R008,00-00-03,111 ST,J,BMT,09/22/2018,00:00:00,REGULAR,6727900,4966445
39793,J035,R008,00-00-01,111 ST,J,BMT,09/22/2018,00:00:00,REGULAR,3221273,2993259
39919,J037,R009,00-00-00,121 ST,JZ,BMT,09/22/2018,00:00:00,REGULAR,3274345,3686366
39961,J037,R009,00-00-01,121 ST,JZ,BMT,09/22/2018,00:00:00,REGULAR,2077950,1162427
...,...,...,...,...,...,...,...,...,...,...,...
65125,N129,R382,00-03-00,GRANT AV,A,IND,09/22/2018,00:00:00,REGULAR,1034215,646059
65083,N129,R382,00-00-01,GRANT AV,A,IND,09/22/2018,00:00:00,REGULAR,9063876,7249301
65041,N129,R382,00-00-00,GRANT AV,A,IND,09/22/2018,00:00:00,REGULAR,1208052082,1761733157
104002,N556,R424,00-00-02,AVENUE P,F,IND,09/22/2018,00:00:00,REGULAR,314003,165453
103956,N556,R424,00-00-01,AVENUE P,F,IND,09/22/2018,00:00:00,REGULAR,4592269,3035070
103910,N556,R424,00-00-00,AVENUE P,F,IND,09/22/2018,00:00:00,REGULAR,8252132,4909269
176387,R423,R429,00-03-01,PELHAM BAY PARK,6,IRT,09/22/2018,00:00:00,REGULAR,16731565,9661709
176429,R423,R429,00-05-00,PELHAM BAY PARK,6,IRT,09/22/2018,00:00:00,REGULAR,150996418,0
176471,R423,R429,00-05-01,PELHAM BAY PARK,6,IRT,09/22/2018,00:00:00,REGULAR,83886080,33554791
176261,R423,R429,00-00-03,PELHAM BAY PARK,6,IRT,09/22/2018,00:00:00,REGULAR,3349552,3451746
176219,R423,R429,00-00-02,PELHAM BAY PARK,6,IRT,09/22/2018,00:00:00,REGULAR,3148793,3720301
176177,R423,R429,00-00-01,PELHAM BAY PARK,6,IRT,09/22/2018,00:00:00,REGULAR,128333,126730
176135,R423,R429,00-00-00,PELHAM BAY PARK,6,IRT,09/22/2018,00:00:00,REGULAR,708629,908466
176345,R423,R429,00-03-00,PELHAM BAY PARK,6,IRT,09/22/2018,00:00:00,REGULAR,1050499,530719
176303,R423,R429,00-00-04,PELHAM BAY PARK,6,IRT,09/22/2018,00:00:00,REGULAR,3391264,2143731
22472,C017,R455,00-00-01,25 ST,R,BMT,09/22/2018,00:00:00,REGULAR,1588925,2412807
22430,C017,R455,00-00-00,25 ST,R,BMT,09/22/2018,00:00:00,REGULAR,4127182,7805060
22514,C017,R455,00-00-02,25 ST,R,BMT,09/22/2018,00:00:00,REGULAR,614969,6221206
189278,R605,R456,00-00-00,HOYT ST,23,IRT,09/22/2018,00:00:00,REGULAR,378515,1803645
189320,R605,R456,00-00-01,HOYT ST,23,IRT,09/22/2018,00:00:00,REGULAR,1995498,3039368
189362,R605,R456,00-00-02,HOYT ST,23,IRT,09/22/2018,00:00:00,REGULAR,375337,351512
189488,R605,R456,00-06-00,HOYT ST,23,IRT,09/22/2018,00:00:00,REGULAR,2876020,1303661
189404,R605,R456,00-00-03,HOYT ST,23,IRT,09/22/2018,00:00:00,REGULAR,313231,383971
189446,R605,R456,00-03-00,HOYT ST,23,IRT,09/22/2018,00:00:00,REGULAR,1628291,3511486
67332,N181A,R464,00-06-03,AQUEDUCT RACETR,A,IND,09/22/2018,00:00:00,REGULAR,50975096,16904291
67290,N181A,R464,00-06-02,AQUEDUCT RACETR,A,IND,09/22/2018,00:00:00,REGULAR,921118,90924
67248,N181A,R464,00-06-01,AQUEDUCT RACETR,A,IND,09/22/2018,00:00:00,REGULAR,1300955,107732
67206,N181A,R464,00-06-00,AQUEDUCT RACETR,A,IND,09/22/2018,00:00:00,REGULAR,986351,139265
67164,N181A,R464,00-05-01,AQUEDUCT RACETR,A,IND,09/22/2018,00:00:00,REGULAR,1,190
67122,N181A,R464,00-05-00,AQUEDUCT RACETR,A,IND,09/22/2018,00:00:00,REGULAR,1697,0

In [24]:
url = 'https://data.cityofnewyork.us/api/views/kk4q-3rt2/rows.csv?accessType=DOWNLOAD'
urllib.request.urlretrieve(url, "subwaystations.csv")
!mv subwaystations.csv $HOME/USAProject2

In [25]:
stns = pd.read_csv(os.getenv('HOME') + '/USAProject2/subwaystations.csv')

In [29]:
stns = stns[['NAME', 'the_geom']]

In [31]:
stns.head()

               NAME                                      the_geom
0          Astor Pl  POINT (-73.99106999861966 40.73005400028978)
1          Canal St  POINT (-74.00019299927328 40.71880300107709)
2           50th St  POINT (-73.98384899986625 40.76172799961419)
3         Bergen St  POINT (-73.97499915116808 40.68086213682956)
4  Pennsylvania Ave  POINT (-73.89488591154061 40.66471445143568)

In [32]:
stns.shape

(473, 2)